"""initial schema

Revision ID: 335dc8719195
Revises: 
Create Date: 2026-03-24 22:43:35.780213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import UserDefinedType


class TSVector(UserDefinedType):
    cache_ok = True
    def get_col_spec(self):
        return "TSVECTOR"

# revision identifiers, used by Alembic.
revision: str = '335dc8719195'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=False),
    sa.Column('bates_begin', sa.String(length=50), nullable=False),
    sa.Column('bates_end', sa.String(length=50), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('text_search_vector', TSVector(), nullable=True),
    sa.Column('native_path', sa.String(length=500), nullable=True),
    sa.Column('image_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_id', 'bates_begin', name='uq_prod_bates')
    )
    op.create_index('ix_documents_bates_begin', 'documents', ['bates_begin'], unique=False)
    op.create_index('ix_documents_bates_end', 'documents', ['bates_end'], unique=False)
    op.create_index('ix_documents_text_search', 'documents', ['text_search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_text_search', table_name='documents', postgresql_using='gin')
    op.drop_index('ix_documents_bates_end', table_name='documents')
    op.drop_index('ix_documents_bates_begin', table_name='documents')
    op.drop_table('documents')
    op.drop_table('productions')
    # ### end Alembic commands ###
