"""add tags notes saved_searches

Revision ID: 8105f7c0d525
Revises: 335dc8719195
Create Date: 2026-03-24 23:18:20.459498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8105f7c0d525'
down_revision: Union[str, Sequence[str], None] = '335dc8719195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('keyboard_shortcut', sa.String(length=5), nullable=True),
    sa.Column('production_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('applied_by', sa.String(length=100), nullable=False),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'tag_id', name='uq_doc_tag')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed default tags
    tags_table = sa.table(
        'tags',
        sa.column('name', sa.String),
        sa.column('category', sa.String),
        sa.column('color', sa.String),
        sa.column('keyboard_shortcut', sa.String),
    )
    op.bulk_insert(tags_table, [
        {'name': 'Responsive', 'category': 'responsiveness', 'color': 'green', 'keyboard_shortcut': 'r'},
        {'name': 'Not Responsive', 'category': 'responsiveness', 'color': 'red', 'keyboard_shortcut': 'n'},
        {'name': 'Needs Review', 'category': 'responsiveness', 'color': 'yellow', 'keyboard_shortcut': 'w'},
        {'name': 'Privileged', 'category': 'privilege', 'color': 'purple', 'keyboard_shortcut': 'p'},
        {'name': 'Not Privileged', 'category': 'privilege', 'color': 'gray', 'keyboard_shortcut': None},
        {'name': 'Needs Privilege Review', 'category': 'privilege', 'color': 'yellow', 'keyboard_shortcut': None},
        {'name': 'Hot Document', 'category': 'issues', 'color': 'red', 'keyboard_shortcut': 'h'},
        {'name': 'Key Document', 'category': 'issues', 'color': 'blue', 'keyboard_shortcut': 'k'},
        {'name': 'Redaction Dispute', 'category': 'issues', 'color': 'purple', 'keyboard_shortcut': None},
        {'name': 'Metadata Gap', 'category': 'issues', 'color': 'yellow', 'keyboard_shortcut': None},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('document_tags')
    op.drop_table('tags')
    op.drop_table('saved_searches')
    # ### end Alembic commands ###
